name: Maven Build

on:
  pull_request:
    branches: [ main ] # adjust as per your branch setup

env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # or whatever version you're using

      - name: Build with Maven
        run: mvn clean verify