name: Maven Build

on:
  pull_request:
    branches: [ main ] # adjust as per your branch setup

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  JWT_TOKEN: ${{ secrets.JWT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # or whatever version you're using

      - name: Build with Maven
        run: mvn clean verify

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
            -Dsonar.java.binaries=backend/target/classes
            -Dsonar.coverage.exclusions=**/test/**,**/exceptions/**,**/schedulers/**,**/Main.java